# Generated by Django 3.2.16 on 2022-12-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_url', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('modality', models.CharField(choices=[('MRI', 'Mri'), ('CT', 'Ct'), ('US', 'Us')], max_length=3)),
            ],
        ),
    ]
