# Generated by Django 3.2.16 on 2022-12-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='instance_url',
            field=models.CharField(default='https://healthcare.googleapis.com/v1', max_length=100),
        ),
        migrations.AlterField(
            model_name='instance',
            name='modality',
            field=models.CharField(choices=[('MRI', 'Mri'), ('CT', 'Ct'), ('US', 'Us'), ('NA', 'Na')], default='NA', max_length=3),
        ),
    ]
